"use strict";
const sb=window.supabase.createClient(window.MUSEUM_SUPABASE_URL,window.MUSEUM_SUPABASE_KEY);

const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
let state={periods:[],content:{},director:{bio:"",photo_path:""},meetings:[],students:[]},currentUser=null,currentPeriod=null,activeRecorder=null,recordedAudioBlob=null;
const authOverlay=$("authOverlay"),siteHeader=$("siteHeader"),siteMain=$("siteMain"),siteFooter=$("siteFooter"),loginForm=$("loginForm"),loginError=$("loginError"),registerTab=$("registerTab"),modal=$("modal"),modalTitle=$("modalTitle"),modalForm=$("modalForm");
const isAdmin=()=>!!currentUser&&(currentUser.role==="admin"||currentUser.role==="developer"),isDev=()=>currentUser?.role==="developer";
function url(bucket,path){return path?sb.storage.from(bucket).getPublicUrl(path).data.publicUrl:""}
function media(bucket,path,type){if(!path)return "";let u=url(bucket,path);return type==="photo"?'<img class="media" src="'+esc(u)+'" alt="Фото">':type==="video"?'<video class="media" controls src="'+esc(u)+'"></video>':'<audio class="media" controls src="'+esc(u)+'"></audio>'}
async function upload(input,bucket,folder){let f=$(input)?.files?.[0];if(!f)return null;return uploadBlob(f,bucket,folder)}\nasync function uploadBlob(f,bucket,folder){let ext=(f.name?.split(".").pop()||((f.type||"application/octet-stream").split("/")[1])||"bin").toLowerCase(),path=folder+"/"+crypto.randomUUID()+"."+ext;let r=await sb.storage.from(bucket).upload(path,f,{contentType:f.type||"application/octet-stream",cacheControl:"3600"});if(r.error)throw r.error;return path}\nasync function toggleRecording(buttonId,statusId){let btn=$(buttonId),status=$(statusId);if(activeRecorder){activeRecorder.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){alert("Браузер не поддерживает запись аудио.");return}try{let stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[],rec=new MediaRecorder(stream);activeRecorder={rec,stream};recordedAudioBlob=null;status.textContent="Идёт запись… нажмите кнопку ещё раз для остановки.";btn.textContent="⏹ Остановить запись";rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{let type=rec.mimeType||"audio/webm";recordedAudioBlob=new Blob(chunks,{type});stream.getTracks().forEach(t=>t.stop());activeRecorder=null;btn.textContent="🎙 Записать аудио";status.textContent="Запись готова. Она будет загружена при сохранении.";};rec.start()}catch(e){status.textContent="Нет доступа к микрофону: "+e.message}}
async function load(){let [p,e,v,d,m,s]=await Promise.all([sb.from("periods").select("*").order("sort_order"),sb.from("exhibits").select("*").order("created_at",{ascending:false}),sb.from("veterans").select("*").order("created_at",{ascending:false}),sb.from("director").select("*").eq("id",1).maybeSingle(),sb.from("meetings").select("*").order("created_at",{ascending:false}),sb.from("students").select("*").order("created_at",{ascending:false})]);let err=[p,e,v,d,m,s].map(x=>x.error).find(Boolean);if(err)throw err;state={periods:p.data||[],content:{},director:d.data||{bio:"",photo_path:""},meetings:m.data||[],students:s.data||[]};(e.data||[]).forEach(x=>(state.content[x.period_id]??={exhibits:[],veterans:[]}).exhibits.push(x));(v.data||[]).forEach(x=>(state.content[x.period_id]??={exhibits:[],veterans:[]}).veterans.push(x))}
async function refresh(){await load();renderAll()}
function showSite(){authOverlay.classList.add("hidden");siteHeader.classList.remove("hidden");siteMain.classList.remove("hidden");siteFooter.classList.remove("hidden");$("currentUser").textContent=currentUser.role==="guest"?"Гость — только просмотр":currentUser.email+" — "+(currentUser.role==="developer"?"Разработчик":"Администратор");registerTab.classList.toggle("hidden",!isDev());renderAll()}
loginForm.addEventListener("submit",async e=>{e.preventDefault();let email=$("login").value.trim(),password=$("password").value;loginError.textContent="";try{let {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;let {data:roleRow,error:roleError}=await sb.from("user_roles").select("role").eq("user_id",data.user.id).maybeSingle();if(roleError)throw roleError;if(!roleRow){await sb.auth.signOut();throw new Error("Для этого пользователя ещё не назначена роль developer или admin.")}currentUser={id:data.user.id,email:data.user.email,role:roleRow.role};await refresh();showSite()}catch(x){loginError.textContent="Ошибка входа: "+x.message}});
$("guestBtn").addEventListener("click",async()=>{currentUser={email:"guest",role:"guest"};try{await refresh();showSite()}catch(x){loginError.textContent="Ошибка подключения к Supabase: "+x.message}});
$("logoutBtn").addEventListener("click",async()=>{await sb.auth.signOut();location.reload()});
document.querySelectorAll("button[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("button[data-tab]").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".section").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
$("backPeriods").onclick=()=>{$("periodDetail").classList.remove("active");$("periodsView").classList.remove("hidden")};
function renderAll(){renderPeriods();renderDirector();renderMeetings();renderStudents();if(isDev())renderAdmins()}
function renderPeriods(){let g=$("periodGrid");g.innerHTML=state.periods.map(p=>'<article class="card period-card" data-id="'+esc(p.id)+'"><div class="period">'+esc(p.title)+'</div><div class="tag">Исторический период</div><h3>Подробнее</h3><p>Открыть экспонаты и ветеранов.</p>'+(isAdmin()?'<div class="actions"><button data-edit-period="'+p.id+'">Редактировать</button><button class="danger" data-del-period="'+p.id+'">Удалить</button></div>':"")+'</article>').join("")+(isAdmin()?'<article class="card"><div class="tag">Управление</div><h3>Добавить период</h3><button id="addPeriod">+ Новый период</button></article>':"");g.querySelectorAll(".period-card").forEach(c=>c.onclick=e=>{if(!e.target.closest("button"))openPeriod(c.dataset.id)});g.querySelectorAll("[data-edit-period]").forEach(b=>b.onclick=()=>periodForm(b.dataset.editPeriod));g.querySelectorAll("[data-del-period]").forEach(b=>b.onclick=async()=>{if(confirm("Удалить период и материалы?")){await sb.from("periods").delete().eq("id",b.dataset.delPeriod);await refresh()}});$("addPeriod")?.addEventListener("click",()=>periodForm())}
function openPeriod(id){currentPeriod=id;$("periodsView").classList.add("hidden");$("periodDetail").classList.add("active");$("periodTitle").textContent=state.periods.find(p=>p.id===id)?.title||"";renderContent()}
function renderContent(){let g=$("contentGrid"),d=state.content[currentPeriod]||{exhibits:[],veterans:[]};g.innerHTML=["exhibits","veterans"].map(k=>{let title=k==="exhibits"?"Экспонаты":"Ветераны",items=d[k]||[];return '<div><div class="card"><div class="tag">Раздел периода</div><h3>'+title+'</h3><div class="search-row"><input type="search" id="search-'+k+'" placeholder="Поиск по названию..."></div>'+(isAdmin()?'<button data-add="'+k+'">+ Добавить</button>':"")+'</div><div id="list-'+k+'" style="margin-top:14px">'+(items.length?items.map(x=>'<article class="card searchable" data-title="'+esc((x.title||"").toLowerCase())+'"><h3>'+esc(x.title)+'</h3><p>'+esc(x.description)+'</p>'+media("museum-photos",x.photo_path,"photo")+media("museum-videos",x.video_path,"video")+media("museum-audio",x.audio_path,"audio")+(isAdmin()?'<div class="actions"><button data-edit="'+k+'" data-id="'+x.id+'">Редактировать</button><button class="danger" data-del="'+k+'" data-id="'+x.id+'">Удалить</button></div>':"")+'</article>').join(""):'<div class="empty">Пока нет материалов.</div>')+'</div></div>'}).join("");["exhibits","veterans"].forEach(k=>{$("search-"+k).oninput=function(){let q=this.value.toLowerCase();$("list-"+k).querySelectorAll(".searchable").forEach(c=>c.classList.toggle("hidden",q&&!c.dataset.title.includes(q)))}});g.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>contentForm(b.dataset.add));g.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>contentForm(b.dataset.edit,b.dataset.id));g.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{if(confirm("Удалить материал?")){await sb.from(b.dataset.del).delete().eq("id",b.dataset.id);await refresh();openPeriod(currentPeriod)}})}
function openModal(t,h){modalTitle.textContent=t;modalForm.innerHTML=h;modal.classList.remove("hidden");modalForm.querySelector("[data-close]")?.addEventListener("click",()=>modal.classList.add("hidden"))}
async function contentForm(k,id){recordedAudioBlob=null;let table=k,o=(state.content[currentPeriod]?.[k]||[]).find(x=>x.id===id)||{};openModal(id?"Редактировать материал":"Добавить материал",'<label>Название</label><input id="fTitle" value="'+esc(o.title)+'" required><label>Описание</label><textarea id="fDesc">'+esc(o.description)+'</textarea><label>Фото</label><input id="fPhoto" type="file" accept="image/*"><label>Видео</label><input id="fVideo" type="file" accept="video/*"><label>Аудио</label><input id="fAudio" type="file" accept="audio/*"><div class="actions"><button type="button" id="recordAudio">🎙 Записать аудио</button><span id="recordStatus" class="notice"></span></div><div class="form-actions"><button type="button" data-close>Отмена</button><button>Сохранить</button></div>');$("recordAudio").onclick=()=>toggleRecording("recordAudio","recordStatus");modalForm.onsubmit=async e=>{e.preventDefault();try{if(activeRecorder)activeRecorder.rec.stop();let r={period_id:currentPeriod,title:$("fTitle").value.trim(),description:$("fDesc").value,photo_path:o.photo_path||null,video_path:o.video_path||null,audio_path:o.audio_path||null};if($("fPhoto").files[0])r.photo_path=await upload("fPhoto","museum-photos","exhibits/"+currentPeriod);if($("fVideo").files[0])r.video_path=await upload("fVideo","museum-videos","exhibits/"+currentPeriod);if($("fAudio").files[0])r.audio_path=await upload("fAudio","museum-audio","exhibits/"+currentPeriod);else if(recordedAudioBlob)r.audio_path=await uploadBlob(new File([recordedAudioBlob],"recording.webm",{type:recordedAudioBlob.type}),"museum-audio","exhibits/"+currentPeriod);if(id)await sb.from(table).update(r).eq("id",id);else await sb.from(table).insert(r);modal.classList.add("hidden");await refresh();openPeriod(currentPeriod)}catch(x){alert("Ошибка: "+x.message)}}}
function periodForm(id){let p=id&&state.periods.find(x=>x.id===id);openModal(id?"Редактировать период":"Новый период",'<label>Период</label><input id="fTitle" value="'+esc(p?.title||"")+'" required><div class="form-actions"><button type="button" data-close>Отмена</button><button>Сохранить</button></div>');modalForm.onsubmit=async e=>{e.preventDefault();let title=$("fTitle").value.trim();if(p)await sb.from("periods").update({title}).eq("id",p.id);else await sb.from("periods").insert({title,sort_order:state.periods.length});modal.classList.add("hidden");await refresh()}}
function renderDirector(){$("directorContent").innerHTML='<article class="card"><h3>Заведующий музеем</h3><p>'+esc(state.director.bio)+'</p>'+media("museum-photos",state.director.photo_path,"photo")+(isAdmin()?'<div class="actions"><button id="editDirector">Редактировать</button></div>':"")+'</article>';$("editDirector")?.addEventListener("click",directorForm)}
function directorForm(){openModal("Биография заведующего музеем",'<label>Биография</label><textarea id="fBio">'+esc(state.director.bio)+'</textarea><label>Фото</label><input id="fPhoto" type="file" accept="image/*"><div class="form-actions"><button type="button" data-close>Отмена</button><button>Сохранить</button></div>');modalForm.onsubmit=async e=>{e.preventDefault();let photo=state.director.photo_path||null;if($("fPhoto").files[0])photo=await upload("fPhoto","museum-photos","director");await sb.from("director").upsert({id:1,bio:$("fBio").value,photo_path:photo,updated_at:new Date().toISOString()});modal.classList.add("hidden");await refresh()}}
function renderMeetings(){let g=$("meetingsList");g.innerHTML=(isAdmin()?'<div class="toolbar"><button id="addMeeting">+ Добавить встречу</button></div>':"")+'<div class="search-row"><input type="search" id="search-meetings" placeholder="Поиск по названию..."></div>'+(state.meetings.length?state.meetings.map(x=>'<article class="card event searchable" data-title="'+esc(x.title.toLowerCase())+'"><b>'+esc(x.date)+'</b><h3>'+esc(x.title)+'</h3><p>'+esc(x.description)+'</p>'+media("museum-videos",x.video_path,"video")+media("museum-audio",x.audio_path,"audio")+(isAdmin()?'<div class="actions"><button data-edit-meeting="'+x.id+'">Редактировать</button><button class="danger" data-del-meeting="'+x.id+'">Удалить</button></div>':"")+'</article>').join(""):'<div class="empty">Встреч пока нет.</div>');$("search-meetings").oninput=function(){let q=this.value.toLowerCase();g.querySelectorAll(".searchable").forEach(c=>c.classList.toggle("hidden",q&&!c.dataset.title.includes(q)))};$("addMeeting")?.addEventListener("click",()=>meetingForm());g.querySelectorAll("[data-edit-meeting]").forEach(b=>b.onclick=()=>meetingForm(b.dataset.editMeeting));g.querySelectorAll("[data-del-meeting]").forEach(b=>b.onclick=async()=>{if(confirm("Удалить встречу?")){await sb.from("meetings").delete().eq("id",b.dataset.delMeeting);await refresh()}})}
function meetingForm(id){recordedAudioBlob=null;let o=state.meetings.find(x=>x.id===id)||{};openModal(id?"Редактировать встречу":"Новая встреча",'<div class="form-row"><div><label>Дата</label><input id="fDate" value="'+esc(o.date)+'"></div><div><label>Название</label><input id="fTitle" value="'+esc(o.title)+'" required></div></div><label>Описание</label><textarea id="fDesc">'+esc(o.description)+'</textarea><label>Видео</label><input id="fVideo" type="file" accept="video/*"><label>Аудио</label><input id="fAudio" type="file" accept="audio/*"><div class="form-actions"><button type="button" data-close>Отмена</button><button>Сохранить</button></div>');$("recordAudio").onclick=()=>toggleRecording("recordAudio","recordStatus");modalForm.onsubmit=async e=>{e.preventDefault();try{if(activeRecorder)activeRecorder.rec.stop();let r={date:$("fDate").value,title:$("fTitle").value,description:$("fDesc").value,video_path:o.video_path||null,audio_path:o.audio_path||null};if($("fVideo").files[0])r.video_path=await upload("fVideo","museum-videos","meetings");if($("fAudio").files[0])r.audio_path=await upload("fAudio","museum-audio","meetings");else if(recordedAudioBlob)r.audio_path=await uploadBlob(new File([recordedAudioBlob],"recording.webm",{type:recordedAudioBlob.type}),"museum-audio","meetings");if(id)await sb.from("meetings").update(r).eq("id",id);else await sb.from("meetings").insert(r);modal.classList.add("hidden");await refresh()}catch(x){alert("Ошибка: "+x.message)}}
function renderStudents(){let g=$("studentsList");g.innerHTML=(isAdmin()?'<div class="toolbar" style="grid-column:1/-1"><button id="addStudent">+ Добавить работу</button></div>':"")+'<div class="search-row" style="grid-column:1/-1"><input type="search" id="search-students" placeholder="Поиск по названию..."></div>'+(state.students.length?state.students.map(x=>'<article class="card searchable"><div class="tag">Работа студента</div><h3>'+esc(x.title)+'</h3><p>'+esc(x.description)+'</p>'+(x.link?'<p><a href="'+esc(x.link)+'" target="_blank" rel="noopener">Открыть работу ↗</a></p>':"")+(isAdmin()?'<div class="actions"><button data-edit-student="'+x.id+'">Редактировать</button><button class="danger" data-del-student="'+x.id+'">Удалить</button></div>':"")+'</article>').join(""):'<div class="empty" style="grid-column:1/-1">Работ пока нет.</div>');$("search-students").oninput=function(){let q=this.value.toLowerCase();g.querySelectorAll(".searchable").forEach(c=>c.classList.toggle("hidden",q&&!c.querySelector("h3").textContent.toLowerCase().includes(q)))};$("addStudent")?.addEventListener("click",()=>studentForm());g.querySelectorAll("[data-edit-student]").forEach(b=>b.onclick=()=>studentForm(b.dataset.editStudent));g.querySelectorAll("[data-del-student]").forEach(b=>b.onclick=async()=>{if(confirm("Удалить работу?")){await sb.from("students").delete().eq("id",b.dataset.delStudent);await refresh()}})}
function studentForm(id){let o=state.students.find(x=>x.id===id)||{};openModal(id?"Редактировать работу":"Новая работа",'<label>Название</label><input id="fTitle" value="'+esc(o.title)+'" required><label>Описание</label><textarea id="fDesc">'+esc(o.description)+'</textarea><label>Ссылка на работу</label><input id="fLink" value="'+esc(o.link||"")+'"><div class="form-actions"><button type="button" data-close>Отмена</button><button>Сохранить</button></div>');modalForm.onsubmit=async e=>{e.preventDefault();let r={title:$("fTitle").value,description:$("fDesc").value,link:$("fLink").value||null};if(id)await sb.from("students").update(r).eq("id",id);else await sb.from("students").insert(r);modal.classList.add("hidden");await refresh()}}
function renderAdmins(){let g=$("adminsList");g.innerHTML="<div class=\"empty\">Пользователи Auth управляются через Supabase. Роли developer/admin хранятся в user_roles.</div>";return;let admins=[];g.innerHTML=admins.length?admins.map((a,i)=>'<article class="card"><div class="tag">Администратор</div><h3>'+esc(a.login)+'</h3><button class="danger" data-del-admin="'+i+'">Удалить</button></article>').join(""):'<div class="empty">Администраторов пока нет.</div>';g.querySelectorAll("[data-del-admin]").forEach(b=>b.onclick=()=>{if(confirm("Удалить администратора?")){admins.splice(+b.dataset.delAdmin,1);localStorage.setItem("museumAdmins",JSON.stringify(admins));renderAdmins()}})}
$("registerForm").addEventListener("submit",e=>{e.preventDefault();$("registerMessage").textContent="Создание пользователей выполняется через Supabase Auth; после создания пользователя ему назначается роль в таблице user_roles."});
modal.onclick=e=>{if(e.target===modal)modal.classList.add("hidden")};
if(window.MUSEUM_SUPABASE_URL?.includes("YOUR-PROJECT")){loginError.textContent="Сначала настройте Supabase: supabase-config.js";$("guestBtn").disabled=true}
